version: "2.0"

services:
  api:
    build: ./server
    ports:
      - "4444:4444"
    container_name: server
  client:
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/src/app/src
    tty: true
    container_name: client
    environment:
      - CHOKIDAR_USEPOLLING=true